added image promotion

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -2,6 +2,9 @@ name: vote-app-pipeline
 on: push
 env:
     serviceName: vote
+    depName: voting-app-deployment
+    containerName: voting-app-container
+    environment: green
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -31,7 +34,17 @@ jobs:
           echo "$KUBE_CONFIG_DATA"
           echo "$KUBE_CONFIG_DATA"|base64 --decode > $HOME/.kube/config
           chmod 600 $HOME/.kube/config
-      - name: verifying cluster access
-        run: kubectl get po
+      - name: updating image
+        run: |
+             kubectl set image deployment/$depName $containerName=${{secrets.ACR_LOGIN_SERVER}}/$serviceName:$SHORT_COMMIT_ID -n $environment
+             kubectl rollout status deployment/$depName --timeout=120s -n $environment
+             if [ $? -ne 0 ];then
+                echo "Deployment failed!,Rollback happening for $depName "
+                kuebctl rollout undo deployment/$depName -n $environment
+             else
+                echo "Deployment successfull"
+
+             fi
+            
 
 
